"""
Database Mixin for BusinessTypeDetectorV2

Extracted from business_type_detector_v2.py to reduce the God Class size.
Contains the keyword and pattern database initialization methods:
- _init_keyword_database_v2: enhanced keyword DB (primary/secondary/context/domain/synonyms)
- _init_pattern_database: regex pattern DB for high-priority matching

=== Design Notes ===
Implemented as a mixin class to preserve all method signatures.
BusinessTypeDetectorV2 inherits from this mixin, so all external callers see no
change. Cross-mixin dependencies are resolved at runtime via the composed
facade instance.
"""

from typing import Dict, Any, List

from opc_manager.business_types import BusinessType


class BusinessTypeDetectorDatabaseMixin:
    """Mixin class containing database initialization methods for
    BusinessTypeDetectorV2.

    These methods build the in-memory keyword and regex pattern databases that
    power the detection pipeline. They are pure factories (no instance state)
    and are invoked once from BusinessTypeDetectorV2.__init__.
    """

    def _init_keyword_database_v2(self) -> Dict[BusinessType, Dict[str, Any]]:
        """
        Initialize enhanced keyword database V2

        Improvements over V1:
        - Expanded primary_keywords (25-35 per type)
        - Added synonyms (synonym mapping)
        - Added domain_phrases (domain-specific phrases)
        - Optimized weight values based on actual test data
        """
        return {
            BusinessType.CONTENT_CREATOR: {
                "name": "内容创作者",
                "emoji": "",
                "weight": 1.6,
                "primary_keywords": [
                    "内容",
                    "创作",
                    "写作",
                    "文章",
                    "博客",
                    "公众号",
                    "小红书",
                    "抖音",
                    "视频",
                    "直播",
                    "UP主",
                    "博主",
                    "粉丝",
                    "涨粉",
                    "爆款",
                    "选题",
                    "日历",
                    "排期",
                    "种草",
                    "完播率",
                    "互动率",
                    "阅读量",
                    "10万+",
                    "流量",
                    "变现",
                    "广告",
                    "品牌合作",
                    "MCN",
                    "笔记",
                    "图文",
                    "短视频",
                    "中视频",
                    "长视频",
                    "投流",
                    "达人",
                    "KOL",
                    "KOC",
                    "矩阵",
                ],
                "secondary_keywords": [
                    "发布",
                    "更新",
                    "推送",
                    "素材",
                    "文案",
                    "标题",
                    "封面",
                    "脚本",
                    "拍摄",
                    "剪辑",
                    "平台",
                    "算法",
                    "推荐",
                    "热搜",
                    "话题",
                    "点赞",
                    "评论",
                    "转发",
                    "收藏",
                    "分享",
                    "粉丝画像",
                    "用户画像",
                    "账号运营",
                ],
                "context_phrases": [
                    "帮我写一篇",
                    "下周发什么",
                    "内容规划",
                    "粉丝画像",
                    "多平台",
                    "矩阵运营",
                    "我的小红书",
                    "我的抖音",
                    "涨粉技巧",
                ],
                "synonyms": {
                    "内容创作": ["自媒体", "新媒体", "内容生产"],
                    "爆款": ["爆文", "热门", " viral"],
                    "粉丝": ["关注者", "订阅者", "读者"],
                },
                "domain_phrases": [
                    "选题库",
                    "热点追踪",
                    "内容分发",
                    "流量池",
                    "私域流量",
                    "公域流量",
                    "账号权重",
                    "垂直度",
                ],
            },
            BusinessType.DIGITAL_PRODUCT: {
                "name": "数字产品开发者",
                "emoji": "",
                "weight": 1.4,
                "primary_keywords": [
                    "数字产品",
                    "知识付费",
                    "课程",
                    "电子书",
                    "模板",
                    "小报童",
                    "Gumroad",
                    "Teachable",
                    "产品上架",
                    "定价",
                    "销售页",
                    "landing page",
                    "漏斗",
                    "付费用户",
                    "订阅",
                    "会员",
                    "社群",
                    "知识星球",
                    "专栏",
                    "训练营",
                    "SaaS",
                    "工具",
                    "插件",
                    "Notion模板",
                    "Excel模板",
                    "PPT模板",
                    "付费阅读",
                    "付费社群",
                    "会员制",
                ],
                "secondary_keywords": [
                    "售卖",
                    "收入",
                    "营收",
                    "转化率",
                    "客单价",
                    "复购",
                    "续费",
                    "退款",
                    "评价",
                    "评分",
                    "产品包装",
                    "USP",
                    "卖点",
                    "价值主张",
                    "预售",
                    "早鸟价",
                    "限时优惠",
                    "满减",
                ],
                "context_phrases": [
                    "我要卖",
                    "如何定价",
                    "写销售页",
                    "产品发布",
                    "上线",
                    "推广课程",
                    "在Gumroad上",
                    "在Teachable上",
                    "知识变现",
                ],
                "synonyms": {
                    "数字产品": ["虚拟产品", "信息产品", "在线课程"],
                    "知识付费": ["知识变现", "付费内容", "付费社群"],
                    "销售页": ["落地页", "Landing Page", "详情页"],
                },
                "domain_phrases": [
                    "价值阶梯",
                    "后端销售",
                    "Upsell",
                    "Cross-sell",
                    "客户终身价值",
                    "LTV",
                    "CAC",
                    "MRR",
                    "ARR",
                ],
            },
            BusinessType.AI_TOOL_BUILDER: {
                "name": "AI工具开发者",
                "emoji": "",
                "weight": 1.5,
                "primary_keywords": [
                    "AI工具",
                    "人工智能",
                    "API",
                    "GPT",
                    "LLM",
                    "ChatGPT",
                    "Claude",
                    "模型",
                    "训练",
                    "微调",
                    "应用",
                    "插件",
                    "扩展",
                    "Agent",
                    "智能助手",
                    "自动化",
                    "代码",
                    "开源",
                    "GitHub",
                    "部署",
                    "用户反馈",
                    "评论",
                    "Issues",
                    "PR",
                    "版本",
                    "功能",
                    "迭代",
                    "路线图",
                    "roadmap",
                    "SDK",
                    "Latency",
                    "Throughput",
                    "Scalability",
                    "Tech Debt",
                    "Refactor",
                    "Deploy",
                    "CI/CD",
                ],
                "secondary_keywords": [
                    "技术文档",
                    "SDK",
                    "集成",
                    "接口",
                    "Token",
                    "调用",
                    "延迟",
                    "性能",
                    "优化",
                    "Bug",
                    "Feature Request",
                    "Changelog",
                    "Release",
                    "Docker",
                    "Kubernetes",
                    "Microservice",
                    "RESTful",
                    "GraphQL",
                    "Webhook",
                    "Rate Limiting",
                    "Caching",
                ],
                "context_phrases": [
                    "我的工具",
                    "用户说",
                    "App Store评论",
                    "GitHub Issues",
                    "新功能",
                    "版本更新",
                    "我的API",
                    "我的应用",
                    "我的产品",
                ],
                "synonyms": {
                    "AI工具": ["人工智能应用", "智能软件", "AI产品"],
                    "API": ["接口", "SDK", "开发包"],
                    "部署": ["上线", "发布", "发布到生产环境"],
                },
                "domain_phrases": [
                    "RICE评分",
                    "MoSCoW法则",
                    "Kano模型",
                    "OKR",
                    "Agile",
                    "Scrum",
                    "Code Review",
                    "TDD",
                    "单元测试",
                    "集成测试",
                    "端到端测试",
                ],
            },
            BusinessType.CONSULTANT: {
                "name": "专业咨询师",
                "emoji": "",
                "weight": 1.3,
                "primary_keywords": [
                    "咨询",
                    "顾问",
                    "提案",
                    "建议书",
                    "方案",
                    "客户",
                    "项目",
                    "服务",
                    "专业",
                    "专家",
                    "战略",
                    "规划",
                    "分析",
                    "研究",
                    "报告",
                    "演示",
                    "汇报",
                    "PPT",
                    "交付物",
                    "合同",
                    "报价",
                    "费用",
                    "时薪",
                    "按项目",
                    "retainer",
                    "方法论",
                    "框架",
                    "SWOT",
                    "PESTEL",
                    "商业模式画布",
                    "价值链分析",
                ],
                "secondary_keywords": [
                    "行业",
                    "市场",
                    "竞争",
                    "痛点",
                    "需求",
                    "解决方案",
                    "最佳实践",
                    "案例",
                    "经验",
                    "洞察",
                    "利益相关者",
                    "Stakeholder",
                    "里程碑",
                    "KPI",
                    "ROI",
                    "投资回报",
                    "验收标准",
                ],
                "context_phrases": [
                    "我的客户",
                    "给客户写",
                    "咨询项目",
                    "服务报价",
                    "专业建议",
                    "客户要做",
                    "帮客户",
                    "为甲方",
                ],
                "synonyms": {
                    "咨询": ["顾问服务", "专业服务", "咨询服务"],
                    "提案": ["建议书", "方案书", "Project Proposal"],
                    "报价": ["费用估算", "价格方案", "Quotation"],
                },
                "domain_phrases": [
                    "SMART原则",
                    "RACI矩阵",
                    "PDCA循环",
                    "五力模型",
                    "BCG矩阵",
                    "安索夫矩阵",
                    "价值主张设计",
                    "精益画布",
                ],
            },
            BusinessType.ECOMMERCE: {
                "name": "电商运营者",
                "emoji": "",
                "weight": 1.4,
                "primary_keywords": [
                    "电商",
                    "淘宝",
                    "天猫",
                    "京东",
                    "拼多多",
                    "店铺",
                    "商品",
                    "SKU",
                    "库存",
                    "订单",
                    "发货",
                    "物流",
                    "快递",
                    "GMV",
                    "销售额",
                    "转化率",
                    "客单价",
                    "访客",
                    "UV",
                    "PV",
                    "直通车",
                    "钻展",
                    "促销",
                    "活动",
                    "双十一",
                    "618",
                    "直播带货",
                    "供应链",
                    "选品",
                    "DSR",
                    "动销率",
                    "复购率",
                    "退货率",
                    "问大家",
                    "好评率",
                    "发货时效",
                ],
                "secondary_keywords": [
                    "详情页",
                    "主图",
                    "标题优化",
                    "SEO",
                    "评价",
                    "退款",
                    "售后",
                    "客服",
                    "旺信",
                    "聚划算",
                    "秒杀",
                    "满减",
                    "优惠券",
                    "红包",
                    "达人带货",
                    "直播间",
                    "品销宝",
                    "超级推荐",
                ],
                "context_phrases": [
                    "我的店铺",
                    "商品上架",
                    "活动报名",
                    "库存预警",
                    "订单处理",
                    "我的淘宝店",
                    "我的京东店",
                    "在拼多多上",
                ],
                "synonyms": {
                    "电商": ["网店", "线上店铺", "电子商务"],
                    "店铺": ["旗舰店", "专营店", "专卖店"],
                    "选品": ["商品开发", "产品开发", "Product Sourcing"],
                },
                "domain_phrases": [
                    "引力魔方",
                    "生意参谋",
                    "数据银行",
                    "人群画像",
                    "投放ROI",
                    "点击率(CTR)",
                    "收藏加购率",
                    "转化漏斗",
                ],
            },
            BusinessType.CREATIVE_WORK: {
                "name": "创意工作者",
                "emoji": "",
                "weight": 1.3,
                "primary_keywords": [
                    "设计",
                    "创意",
                    "作品",
                    "交付",
                    "客户",
                    "UI",
                    "UX",
                    "平面",
                    "品牌",
                    "logo",
                    "插画",
                    "摄影",
                    "视频制作",
                    "剪辑",
                    "作品集",
                    "portfolio",
                    "提案",
                    "样机",
                    "Figma",
                    "Sketch",
                    "Photoshop",
                    "AI绘画",
                    "Midjourney",
                    "Stable Diffusion",
                    "DALL-E",
                    "排版",
                    "配色",
                    "字体",
                    "图标",
                    "视觉",
                    "品牌VI",
                    "包装设计",
                    "海报",
                    "H5页面",
                ],
                "secondary_keywords": [
                    "视觉",
                    "配色",
                    "排版",
                    "字体",
                    "图标",
                    "原型",
                    "交互",
                    "动效",
                    "渲染",
                    "素材",
                    "版权",
                    "商用",
                    "授权",
                    "样机",
                    "Mockup",
                    "Design System",
                    "Style Guide",
                ],
                "context_phrases": [
                    "设计稿",
                    "效果图",
                    "客户反馈",
                    "作品集整理",
                    "创意方案",
                    "我的设计",
                    "帮做个logo",
                    "设计个海报",
                ],
                "synonyms": {
                    "设计": ["Design", "视觉设计", "平面设计"],
                    "作品集": ["Portfolio", "案例集", "作品展示"],
                    "交付": ["交付物", "Final Delivery", "终稿"],
                },
                "domain_phrases": [
                    "极简主义",
                    "孟菲斯风格",
                    "赛博朋克",
                    "日式禅意",
                    "北欧风",
                    "波普艺术",
                    "扁平化",
                    "新拟态",
                    "玻璃拟态",
                ],
            },
        }

    def _init_pattern_database(self) -> Dict[BusinessType, List[str]]:
        """
        Initialize pattern database

        Patterns are higher-order expression forms than keywords,
        capturing specific grammatical structures and semantic intent
        """
        return {
            BusinessType.CONTENT_CREATOR: [
                r"帮我写.*?(文章|笔记|文案|内容)",
                r"(小红书|抖音|公众号|B站).*(运营|管理|规划)",
                r".*?(涨粉|增粉|吸粉).*?",
                r".*?(爆款|爆文|10万\+).*?",
                r".*?(选题|内容日历|排期).*?",
                r"我的.*(账号|博主|UP主)",
            ],
            BusinessType.DIGITAL_PRODUCT: [
                r"(售卖|出售|上架).*(课程|电子书|模板|产品)",
                r"(Gumroad|Teachable|小报童|知识星球).*(发布|上架|开设)",
                r".*?(定价|价格|收费).*?(课程|产品|内容)",
                r".*?(销售页|Landing Page|详情页).*?(撰写|优化|设计)",
                r".*?(知识付费|付费内容|付费社群).*?",
            ],
            BusinessType.AI_TOOL_BUILDER: [
                r"(我的|开发|构建).*(工具|应用|API|产品).*(AI|人工智能|GPT|LLM)",
                r".*?(App Store|GitHub|Product Hunt).*(评论|反馈|Issues)",
                r".*?(版本|迭代|更新|发布).*(日志|说明|Notes)",
                r".*?(性能|优化|延迟|Latency|速度).*?(提升|改进|优化)",
                r".*?(用户反馈|User Feedback|评论).*?(分析|处理|回复)",
            ],
            BusinessType.CONSULTANT: [
                r"(给|为|帮).*(客户|甲方).*(写|做|起草).*?(方案|报告|提案|建议书)",
                r".*?(咨询|顾问|专家).*?(服务|项目|报价)",
                r".*?(SWOT|PESTEL|商业模式|战略).*?(分析|规划|制定)",
                r".*?(报价|费用|时薪|预算).*?(方案|明细|清单)",
                r".*?(方法论|框架|模型).*?(应用|使用|实施)",
            ],
            BusinessType.ECOMMERCE: [
                r"(我的|帮).*(店铺|淘宝|京东|拼多多).*(运营|管理|优化)",
                r".*?(商品|产品|SKU).*(上架|发布|编辑|优化)",
                r".*?(促销|活动|大促|双十一|618).*(策划|方案|准备)",
                r".*?(库存|补货|供应链).*(预警|管理|优化)",
                r".*?(GMV|销售额|转化率|ROI).*(提升|分析|优化)",
            ],
            BusinessType.CREATIVE_WORK: [
                r"(帮我|给我).*(设计|做|画|创.*?作).*(logo|海报|UI|界面|插画|图片)",
                r".*?(Figma|Sketch|Photoshop|AI绘画|Midjourny).*?(文件|源件|设计稿)",
                r".*?(作品集|Portfolio|案例).*?(整理|更新、优化)",
                r".*?(设计稿|效果图|样机).*(交付|提交|发送)",
                r".*?(品牌|VI|视觉).*(设计|升级、规范)",
            ],
        }
