"""
Settings Manager — v0.3.27 统一设置中心

提供运行时可修改的用户设置，支持持久化到JSON文件。
所有敏感信息通过SecureKeyStore加密存储。

设计原则：
- 与 ConfigManager（只读env）互补：ConfigManager管系统配置，SettingsManager管用户偏好
- 线程安全单例模式：全局唯一实例，支持多线程并发访问
- 敏感字段掩码：导出时自动脱敏，防止密钥泄露
- 原子写入：使用临时文件+rename保证数据一致性

=== Mixin Architecture (God Class refactor) ===
``SettingsManager`` was split into a thin facade (this file) plus three mixin
modules to keep each file focused and under the line-count budget. The facade
inherits all mixins, so the public API is 100% backward compatible — every
existing importer site keeps working unchanged.

    SettingsManager(SettingsEncryptionMixin, SettingsPersistenceMixin,
                    SettingsOperationsMixin)

Modules:
- ``opc_manager.settings_encryption.SettingsEncryptionMixin``
  Fernet init, encrypt/decrypt helpers, key auto-generation, key heuristics.
- ``opc_manager.settings_persistence.SettingsPersistenceMixin``
  JSON load/save, sensitive-field decryption, plaintext->encrypted migration,
  env-var fallback, SecureKeyStore bridge.
- ``opc_manager.settings_operations.SettingsOperationsMixin``
  SMTP connection test, is_configured, callback registry, masked export,
  reset_to_defaults.

This facade retains:
- The dataclasses/enums (``SettingsCategory``, ``LLMSettings``, ...) and the
  ``SMTP_PRESETS`` constant — they are referenced directly by the getters and
  updaters below, so keeping them here avoids any circular import.
- The singleton plumbing (``__new__`` + class-level ``_lock`` + ``__init__``).
- The property accessors, getters, updaters, and SMTP-preset helpers.
- The ``get_settings()`` factory.

Cross-mixin calls resolve at runtime through ``self`` (e.g. an updater calls
``self._save_to_disk()`` which lives on the persistence mixin).

Usage:
    from opc_manager.settings import get_settings, SettingsManager, SettingsCategory

    settings = get_settings()
    settings.update_llm(provider="moka", api_key="sk-xxx", model="moka/claude-sonnet-4-6")
    print(settings.llm.provider)  # "moka"
"""

import logging
import os
import threading
from dataclasses import dataclass
from enum import Enum
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional

from opc_manager.config import LLM_PROVIDERS
from opc_manager.settings_encryption import SettingsEncryptionMixin
from opc_manager.settings_operations import SettingsOperationsMixin
from opc_manager.settings_persistence import SettingsPersistenceMixin

logger = logging.getLogger(__name__)


class SettingsCategory(Enum):
    """Settings category enumeration for type-safe category references."""

    LLM = "llm"
    SMTP = "smtp"
    API_KEYS = "api_keys"
    SECURITY = "security"
    PROFILE = "profile"


@dataclass
class LLMSettings:
    """LLM provider configuration settings.

    Attributes:
        provider: LLM service provider (moka/glm/openai/ollama)
        api_key: API key for the provider (sensitive field)
        base_url: API endpoint URL
        model: Model identifier string
        max_tokens: Maximum token limit for responses
        temperature: Sampling temperature (0.0-2.0)
    """

    provider: str = "moka"
    api_key: str = ""
    base_url: str = ""
    model: str = ""
    max_tokens: int = 4000
    temperature: float = 0.7


@dataclass
class SMTPSettings:
    """Email SMTP server configuration.

    Attributes:
        host: SMTP server hostname
        port: SMTP server port (typically 465 for SSL, 587 for TLS)
        username: Authentication username
        password: Authentication password (sensitive field)
        tls: Whether to use TLS encryption
        from_email: Sender email address
    """

    host: str = ""
    port: int = 587
    username: str = ""
    password: str = ""
    tls: bool = True
    from_email: str = ""


@dataclass
class SecuritySettings:
    """Security and encryption settings.

    Attributes:
        encryption_key: Master encryption key (displayed as mask, stored in SecureKeyStore)
        auto_generated: Whether key was auto-generated by system
    """

    encryption_key: str = ""
    auto_generated: bool = False


@dataclass
class ProfileSettings:
    """User profile and localization settings.

    Attributes:
        user_name: Display name of the user
        company_name: Organization name
        timezone: User's timezone (IANA format)
        language: UI language code (zh_CN/en_US)
    """

    user_name: str = ""
    company_name: str = ""
    timezone: str = "Asia/Shanghai"
    language: str = "zh_CN"


SMTP_PRESETS = {
    "QQ邮箱": {"host": "smtp.qq.com", "port": 465, "tls": True},
    "163邮箱": {"host": "smtp.163.com", "port": 465, "tls": True},
    "Gmail": {"host": "smtp.gmail.com", "port": 587, "tls": True},
    "Outlook": {"host": "smtp-mail.outlook.com", "port": 587, "tls": True},
}


class SettingsManager(
    SettingsEncryptionMixin,
    SettingsPersistenceMixin,
    SettingsOperationsMixin,
):
    """Unified settings manager for OPC-Agents v0.3.27

    Thread-safe singleton that manages all user-configurable settings.
    Supports runtime modification with JSON persistence and SecureKeyStore
    integration for sensitive fields.

    Architecture:
        ConfigManager (read-only env) ←→ SettingsManager (writable user prefs)

        This class is a thin facade over three mixin modules (see the module
        docstring): encryption, persistence, and operations. All behavior is
        implemented in the mixins; this facade holds the singleton plumbing,
        the dataclasses/enums, the property accessors, the getters, and the
        updaters.

    Thread Safety:
        - Singleton creation protected by class-level lock
        - Data modifications protected by instance-level RLock
        - Callback notifications serialized through lock

    Persistence:
        - Settings stored in data/settings.json (user-editable)
        - Encryption key stored in .env.local (not committed to git)
        - Atomic writes via temp file + os.replace()

    Sensitive Fields:
        - api_key, password, encryption_key are masked on export
        - Actual values persisted in JSON but should use SecureKeyStore in production

    Example:
        >>> settings = get_settings()
        >>> settings.update_llm(provider="openai", api_key="sk-...")
        >>> settings.export_settings()['llm']['api_key']
        '***'
    """

    _instance = None
    _lock = threading.Lock()
    _initialized: bool = False

    SETTINGS_FILE = "data/settings.json"
    SENSITIVE_FIELDS = {"api_key", "password", "encryption_key"}

    def __new__(cls) -> "SettingsManager":
        if cls._instance is None:
            with cls._lock:
                if cls._instance is None:
                    cls._instance = super().__new__(cls)
                    cls._instance._initialized = False
        return cls._instance

    def __init__(self) -> None:
        if not self._initialized:
            self._settings_file = Path(self.SETTINGS_FILE)
            self._data_lock = threading.RLock()
            self._callbacks: List[Callable[[str], None]] = []
            self._llm = LLMSettings()
            self._smtp = SMTPSettings()
            self._security = SecuritySettings()
            self._profile = ProfileSettings()
            self._fernet = None
            self._ensure_encryption_key()
            self._init_fernet()
            self._load_from_disk()
            self._initialized = True

    @property
    def llm(self) -> LLMSettings:
        """Access LLM configuration settings."""
        return self._llm

    @property
    def smtp(self) -> SMTPSettings:
        """Access SMTP configuration settings."""
        return self._smtp

    @property
    def security(self) -> SecuritySettings:
        """Access security configuration settings."""
        return self._security

    @property
    def profile(self) -> ProfileSettings:
        """Access user profile settings."""
        return self._profile

    def get_encryption_key(self) -> str:
        """获取加密密钥，供其他模块使用（不通过 os.environ）。

        Returns:
            加密密钥字符串
        """
        return self._security.encryption_key

    def get_api_key(self, provider: str = "moka") -> Optional[str]:
        """获取指定提供商的 API 密钥（不通过 os.environ）。

        Args:
            provider: 提供商名称（moka/glm/openai）

        Returns:
            API 密钥字符串，未找到返回 None
        """
        key_map = {
            "moka": "MOKA_API_KEY",
            "glm": "GLM_API_KEY",
            "openai": "OPENAI_API_KEY",
        }
        env_key = key_map.get(provider, f"{provider.upper()}_API_KEY")

        # 优先从内存中的设置获取
        if provider == "moka" and self._llm.api_key:
            return self._llm.api_key

        # 从 SecureKeyStore 获取
        value = self._retrieve_sensitive_key(env_key)
        if value:
            return value

        # 回退到 os.environ（兼容外部设置的环境变量）
        return os.environ.get(env_key)

    def get_llm_config(self) -> Dict[str, str]:
        """获取完整的 LLM 配置（不通过 os.environ）。

        Returns:
            包含 api_key, base_url, model 的字典
        """
        config = {
            "api_key": self._llm.api_key or self.get_api_key(self._llm.provider) or "",
            "base_url": self._llm.base_url
            or self._retrieve_sensitive_key("MOKA_API_BASE")
            or os.environ.get("MOKA_API_BASE", LLM_PROVIDERS["moka"]),
            "model": self._llm.model
            or self._retrieve_sensitive_key("MOKA_MODEL")
            or os.environ.get("MOKA_MODEL", "moka/claude-sonnet-4-6"),
        }
        return config

    def get_smtp_config(self) -> Dict[str, str]:
        """获取 SMTP 配置（不通过 os.environ）。

        Returns:
            包含 host, port, username, password, tls, from_email 的字典
        """
        return {
            "host": self._smtp.host
            or self._retrieve_sensitive_key("OPC_SMTP_HOST")
            or "",
            "port": str(self._smtp.port),
            "username": self._smtp.username
            or self._retrieve_sensitive_key("OPC_SMTP_USER")
            or "",
            "password": self._smtp.password
            or self._retrieve_sensitive_key("OPC_SMTP_PASS")
            or "",
            "tls": str(self._smtp.tls),
            "from_email": self._smtp.from_email,
        }

    def update_llm(self, **kwargs: Any) -> bool:
        """Update LLM settings with validation and persistence.

        Args:
            **kwargs: Field names and values to update (provider, api_key, etc.)

        Returns:
            True if update succeeded (always returns True currently,
            may add validation logic later)

        Side effects:
            - Updates os.environ for immediate LLM client use
            - Triggers registered callbacks
            - Persists to disk
        """
        # Validate base_url before applying
        if "base_url" in kwargs:
            url = kwargs["base_url"]
            if url and not (url.startswith("http://") or url.startswith("https://")):
                logger.warning(
                    "Invalid LLM_BASE_URL rejected (must start with http:// or https://): %s",
                    url,
                )
                return False

        valid_fields = {k for k in dir(LLMSettings) if not k.startswith("_")}
        for k, v in kwargs.items():
            if k in valid_fields:
                setattr(self._llm, k, v)
            else:
                logger.warning("Unknown LLM setting field: %s", k)

        self._save_to_disk()
        self._notify_callbacks("llm")

        if kwargs.get("api_key"):
            self._store_sensitive_key("MOKA_API_KEY", kwargs["api_key"])
        if kwargs.get("base_url"):
            self._store_sensitive_key("MOKA_API_BASE", kwargs["base_url"])
        if kwargs.get("model"):
            self._store_sensitive_key("MOKA_MODEL", kwargs["model"])

        return True

    def update_smtp(self, **kwargs: Any) -> bool:
        """Update SMTP settings with validation and persistence.

        Args:
            **kwargs: Field names and values to update (host, port, etc.)

        Returns:
            True if update succeeded

        Side effects:
            - Updates os.environ for email sending modules
            - Triggers callbacks and persists to disk
        """
        # Validate port number before applying
        if "port" in kwargs:
            port = kwargs["port"]
            if not isinstance(port, int) or port < 1 or port > 65535:
                logger.warning("Invalid SMTP port rejected (must be 1-65535): %s", port)
                return False

        valid_fields = {k for k in dir(SMTPSettings) if not k.startswith("_")}
        for k, v in kwargs.items():
            if k in valid_fields:
                setattr(self._smtp, k, v)
            else:
                logger.warning("Unknown SMTP setting field: %s", k)

        self._save_to_disk()
        self._notify_callbacks("smtp")

        if kwargs.get("host"):
            self._store_sensitive_key("OPC_SMTP_HOST", kwargs["host"])
        if kwargs.get("username"):
            self._store_sensitive_key("OPC_SMTP_USER", kwargs["username"])
        if kwargs.get("password"):
            self._store_sensitive_key("OPC_SMTP_PASS", kwargs["password"])

        return True

    def update_profile(self, **kwargs: Any) -> bool:
        """Update user profile settings.

        Args:
            **kwargs: Field names and values (user_name, company_name, etc.)

        Returns:
            True if update succeeded
        """
        valid_fields = {k for k in dir(ProfileSettings) if not k.startswith("_")}
        for k, v in kwargs.items():
            if k in valid_fields:
                setattr(self._profile, k, v)
            else:
                logger.warning("Unknown profile setting field: %s", k)

        self._save_to_disk()
        self._notify_callbacks("profile")
        return True

    def get_smtp_preset(self, name: str) -> Dict[str, Any]:
        """Get SMTP preset configuration by provider name.

        Args:
            name: Provider name (e.g., "QQ邮箱", "Gmail")

        Returns:
            Dict with host, port, tls keys or empty dict if not found
        """
        return SMTP_PRESETS.get(name, {}).copy()

    def get_all_presets(self) -> List[str]:
        """List all available SMTP preset provider names.

        Returns:
            List of provider name strings
        """
        return list(SMTP_PRESETS.keys())


def get_settings() -> SettingsManager:
    """Get the SettingsManager singleton instance.

    This is the recommended way to access settings throughout the application.
    Ensures only one instance exists per process.

    Returns:
        The global SettingsManager singleton instance

    Example:
        >>> from opc_manager.settings import get_settings
        >>> settings = get_settings()
        >>> settings.update_llm(provider="openai")
    """
    return SettingsManager()


__all__ = [
    "SettingsCategory",
    "LLMSettings",
    "SMTPSettings",
    "SecuritySettings",
    "ProfileSettings",
    "SMTP_PRESETS",
    "SettingsManager",
    "get_settings",
]
